#!/usr/bin/env python3
"""Generate skill indexes and the plugin manifest from SKILL.md frontmatter."""

import argparse
import json
import re
import sys
from pathlib import Path


BUCKETS = ("engineering", "interview")
GENERATED = "<!-- Generated by scripts/generate-skill-metadata.py from SKILL.md frontmatter. -->"


def read_frontmatter(path):
    lines = path.read_text().splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path}: missing YAML frontmatter")

    try:
        end = lines.index("---", 1)
    except ValueError as error:
        raise ValueError(f"{path}: unterminated YAML frontmatter") from error

    fields = {}
    metadata = lines[1:end]
    index = 0
    while index < len(metadata):
        match = re.match(r"^([a-zA-Z0-9_-]+):\s*(.*)$", metadata[index])
        if not match:
            index += 1
            continue

        key, value = match.groups()
        index += 1
        if value in {"|", ">"}:
            parts = []
            while index < len(metadata) and (
                metadata[index].startswith((" ", "\t")) or not metadata[index].strip()
            ):
                if metadata[index].strip():
                    parts.append(metadata[index].strip())
                index += 1
            value = " ".join(parts)
        elif len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        fields[key] = " ".join(value.split())

    for required in ("name", "description"):
        if not fields.get(required):
            raise ValueError(f"{path}: missing {required}")
    return fields


def load_skills(root):
    skills = {}
    names = set()
    for bucket in BUCKETS:
        bucket_skills = []
        for path in sorted((root / "skills" / bucket).glob("*/SKILL.md")):
            metadata = read_frontmatter(path)
            name = metadata["name"]
            if name != path.parent.name:
                raise ValueError(f"{path}: name must match directory {path.parent.name!r}")
            if name in names:
                raise ValueError(f"duplicate skill name: {name}")
            names.add(name)
            bucket_skills.append((name, metadata["description"]))
        skills[bucket] = sorted(bucket_skills)
    return skills


def skill_bullets(bucket, skills, root_readme=False):
    prefix = f"./skills/{bucket}/" if root_readme else "./"
    return [
        f"- **[{name}]({prefix}{name}/SKILL.md)** — "
        f"{description.replace('<', '&lt;').replace('>', '&gt;')}"
        for name, description in skills[bucket]
    ]


def render_root_readme(current, skills):
    heading = "## Skills"
    if heading not in current:
        raise ValueError("README.md: missing Skills heading")

    lines = [heading, "", GENERATED]
    for bucket in BUCKETS:
        lines.extend(["", f"### {bucket.title()}", ""])
        lines.extend(skill_bullets(bucket, skills, root_readme=True))
    return current.split(heading, 1)[0].rstrip() + "\n\n" + "\n".join(lines) + "\n"


def render_bucket_readme(current, bucket, skills):
    lines = current.splitlines()
    indexes = [index for index, line in enumerate(lines) if line.startswith("- **[")]
    if not indexes:
        raise ValueError(f"skills/{bucket}/README.md: missing skill list")

    start = indexes[0]
    end = start
    while end < len(lines) and lines[end].startswith("- **["):
        end += 1

    replacement = skill_bullets(bucket, skills)
    if GENERATED not in lines[:start]:
        replacement = [GENERATED, ""] + replacement
    return "\n".join(lines[:start] + replacement + lines[end:]).rstrip() + "\n"


def outputs(root, skills):
    generated = {}
    readme = root / "README.md"
    generated[readme] = render_root_readme(readme.read_text(), skills)

    for bucket in BUCKETS:
        readme = root / "skills" / bucket / "README.md"
        generated[readme] = render_bucket_readme(readme.read_text(), bucket, skills)

    manifest = {
        "name": "engineering-skills",
        "skills": [
            f"./skills/{bucket}/{name}"
            for bucket in BUCKETS
            for name, _ in skills[bucket]
        ],
    }
    generated[root / ".claude-plugin" / "plugin.json"] = json.dumps(manifest, indent=2) + "\n"
    return generated


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail when generated files are stale")
    args = parser.parse_args()

    root = Path(__file__).resolve().parent.parent
    try:
        skills = load_skills(root)
        generated = outputs(root, skills)
    except ValueError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    stale = [path for path, content in generated.items() if path.read_text() != content]
    if args.check:
        for path in stale:
            print(f"stale: {path.relative_to(root)}")
        if stale:
            return 1
        print(f"skill metadata is current ({sum(map(len, skills.values()))} skills)")
        return 0

    for path in stale:
        path.write_text(generated[path])
        print(f"updated {path.relative_to(root)}")
    print(f"indexed {sum(map(len, skills.values()))} skills")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
